---
vagrant:
 private_ip: "10.1.1.100"
 host_name: "srv-fireguard"
 box_name: "ubuntu/xenial64"
 box_url: "ubuntu/xenial64"
 check_update: false
 synced_folder: "./../../Projects"  # Relative Path to Project
 nfs: true
 memory: 2000  # 2 GB
 cpus: 1
 gui: false
 log_file: "/vagrant/vagrant.log"

forwarders: # Format: service_port: host_port
   80: 80
   443: 443
   3306: 3306

start:  ## Define services for start
  - bootstrap
  - php
  - nginx
  - composer
  - git
  - unzip
  - nodejs
  - npm
  - mysql
  - redis
  - ruby

services:
  bootstrap:
    - "America/Sao_Paulo" # timezone
    - "fireguard.dev" # dev domain

  php:
    - "default"      # version [default, 7.0, 5.6]

  nginx:
    - "default"  # version [default, 5.7]

  apache:
    - "default"  # version

  mysql:
    - "default"  # version
    - "password" # Password for root

  git:
    - "Your Name"       # user name
    - "your@email.com"  # email

  nodejs:
    - "default" # version [default, 4, 6]
    
  ruby:
    - "default" # version [default]
    - "compass" # packages
