---
vagrant:
 private_ip: "10.1.1.100"
 host_name: "srv-fireguard"
 box_name: "ubuntu/xenial64"
 box_url: "ubuntu/xenial64"
 check_update: false
 synced_folder: "./../../Projects"
 nfs: false
 memory: 2000  # 2 GB
 cpus: 2
 gui: false
 log_file: "/vagrant/vagrant.log"
 domain_dev: "fireguard.dev"

forwarders: # Format: service_port: host_port
   80: 80
   443: 443
   3306: 3306

start:  ## Define services for start
  - php
  - nginx

services:
  bootstrap:
    - "America/Sao_Paulo" # timezone

  php:
    - "7.0"      # version [default, 5.6, 7.0]

  nginx:
    - "default"  # version

  apache:
    - "default"  # version

  mysql:
    - "default"  # version

  git:
    - "Your Name"       # user name
    - "your@email.com"  # email
